### ISSUE TITLE
nice bug

### ISSUE THREAD

**Issue by BadySmith** [up2code/sample-bot#2]
/opt/apps/bot-discord/ESPRIT-SPART/bot/myBot.js:8
botRem.on('ready', () => {
                    ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
root@serv1:/opt/apps/bot-discord/ESPRIT-SPART/bot#

**Comment by up2code** [comment]
Try using normal function call instead of arrow function.
```javascript
botRem.on('ready', function() {
});

botRem.on('message', function(message) {
  // Your logic
});
```

**Comment by BadySmith** [comment]
thanks is fonctionel, i have other probleme "Bot crasher for 4 days Running in the screen debian 8"

i go creating script Bash Automatic Restart for 1 Hours "Anti crash"

**Comment by BadySmith** [comment]
Is closed
